Add IAP validation APIs for purchase receipts.
heroiclabs/nakama-dotnet pull request #56
Opened 2021-04-10 16:36 UTC by novabyte

2021-04-13 14:28 UTC, lugehorsam requested changes

2021-04-13 14:28 UTC, lugehorsam commented on src/Nakama/ApiClient.gen.cs
> +    }
Looks like there is a problem with the code generator and nested enums.

2021-04-27 22:50 UTC, lugehorsam commented
I added enum support and regenerated the code using the version of our apigrpc.swagger.json found here: https://github.com/heroiclabs/nakama/releases/tag/v3.2.1

For some reason, some of the message types in the generated swagger file have a `title` instead of a `description`.  This affects the comments on some of the generated C# types. I don't know if you used a different version to generate the inner api client.

2021-05-05 22:21 UTC, novabyte commented
@lugehorsam I'm not sure why the generated Swagger spec uses a mixture of `"title"` and `"description"` now. It could be due to one of the recent upgrades we did to the protoc GRPC-Gateway plugin version used by the server. I think this work is good to merge 👍

2021-05-05 23:10 UTC, merged